### ISSUE TITLE
TypeError: Cannot read property 'writable' of undefined

### ISSUE THREAD

**Issue by narbehaj** [sadra/EasyMTPorto#4]
I'm getting this error once a day:

```/root/EasyMTProto/emtproto.js:257
                    if (!socket.server_socket.writable) {
                                              ^

TypeError: Cannot read property 'writable' of undefined
    at Socket.<anonymous> (/root/EasyMTProto/emtproto.js:257:47)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by sadra** [comment]
which javascript and nodejs version do you use?

**Comment by narbehaj** [comment]
`nodejs v10.5.0` and `nodemon 1.17.5`
